-- ALTER TABLE ventaarticulo ADD COLUMN Puntos BOOLEAN NOT NULL;
-- ALTER TABLE VEnta ADD COLUMN CostoTotal INT NOT NULL;
SELECT  FROM_UNIXTIME(UNIX_TIMESTAMP(curdate()) + FLOOR(0 + (RAND() * (2628000-1296000)+1296000)));